# Generated by Django 3.2 on 2024-01-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paragraphsearch', '0002_alter_paragraph_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='paragraph',
            name='unique_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='words',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='words',
            field=models.ManyToManyField(to='paragraphsearch.Word'),
        ),
    ]
